[package]
name = "waddle"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = "0.15.7"
poise = "0.7.0"
rand = "0.10.2"
sysinfo = "0.39.6"
tokio = { version = "1.53.1", features = ["rt-multi-thread"] }

[lints.clippy]
pedantic = { level = "warn", priority = -1 }
unwrap_used = "warn"
expect_used = "warn"
panic = "warn"
todo = "warn"
unimplemented = "warn"
unreachable = "warn"
dbg_macro = "warn"
redundant_clone = "warn"
print_stdout = "warn"
